import java.util.Calendar;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guest
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    public NewJFrame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        bbb = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ccc = new javax.swing.JComboBox<String>();
        sss = new javax.swing.JLabel();
        aaa = new javax.swing.JComboBox<String>();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        c1 = new javax.swing.JCheckBox();
        c11 = new javax.swing.JCheckBox();
        c14 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c10 = new javax.swing.JCheckBox();
        c12 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c15 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c13 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 530, 130, 40);

        bbb.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(bbb);
        bbb.setBounds(270, 130, 140, 30);

        jButton1.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jButton1.setText("Check seats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 390, 230, 50);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Date  =>");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 140, 110, 15);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("theatre no. =>");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 220, 100, 15);

        ccc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        jPanel1.add(ccc);
        ccc.setBounds(270, 220, 140, 30);
        jPanel1.add(sss);
        sss.setBounds(0, 0, 0, 0);

        aaa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "twilight", "spiderman", "avenger" }));
        aaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaaActionPerformed(evt);
            }
        });
        jPanel1.add(aaa);
        aaa.setBounds(270, 180, 140, 30);

        jButton4.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jButton4.setText("Proceed");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(610, 460, 180, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Movie  =>");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 180, 110, 14);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("check movies & seats.... ,then book");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 10, 740, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seats\n\n", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 255, 153))); // NOI18N
        jPanel2.setOpaque(false);

        c1.setBackground(java.awt.Color.green);
        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("1");
        c1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c1.setBorderPainted(true);
        c1.setEnabled(false);
        c1.setOpaque(false);

        c11.setBackground(java.awt.Color.green);
        c11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c11.setForeground(new java.awt.Color(255, 255, 255));
        c11.setText("11");
        c11.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c11.setBorderPainted(true);
        c11.setEnabled(false);
        c11.setOpaque(false);

        c14.setBackground(java.awt.Color.green);
        c14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c14.setForeground(new java.awt.Color(255, 255, 255));
        c14.setText("14");
        c14.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c14.setBorderPainted(true);
        c14.setEnabled(false);
        c14.setOpaque(false);

        c8.setBackground(java.awt.Color.green);
        c8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c8.setForeground(new java.awt.Color(255, 255, 255));
        c8.setText("8");
        c8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c8.setBorderPainted(true);
        c8.setEnabled(false);
        c8.setOpaque(false);

        c10.setBackground(java.awt.Color.green);
        c10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c10.setForeground(new java.awt.Color(255, 255, 255));
        c10.setText("10");
        c10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c10.setBorderPainted(true);
        c10.setEnabled(false);
        c10.setOpaque(false);

        c12.setBackground(java.awt.Color.green);
        c12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c12.setForeground(new java.awt.Color(255, 255, 255));
        c12.setText("12");
        c12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c12.setBorderPainted(true);
        c12.setEnabled(false);
        c12.setOpaque(false);
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });

        c6.setBackground(java.awt.Color.green);
        c6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setText("6");
        c6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c6.setBorderPainted(true);
        c6.setEnabled(false);
        c6.setOpaque(false);

        c4.setBackground(java.awt.Color.green);
        c4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setText("4");
        c4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c4.setBorderPainted(true);
        c4.setEnabled(false);
        c4.setOpaque(false);

        c15.setBackground(java.awt.Color.green);
        c15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c15.setForeground(new java.awt.Color(255, 255, 255));
        c15.setText("15");
        c15.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c15.setBorderPainted(true);
        c15.setEnabled(false);
        c15.setOpaque(false);

        c7.setBackground(java.awt.Color.green);
        c7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c7.setForeground(new java.awt.Color(255, 255, 255));
        c7.setText("7");
        c7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c7.setBorderPainted(true);
        c7.setEnabled(false);
        c7.setOpaque(false);
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        c3.setBackground(java.awt.Color.green);
        c3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setText("3");
        c3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c3.setBorderPainted(true);
        c3.setEnabled(false);
        c3.setOpaque(false);
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c13.setBackground(java.awt.Color.green);
        c13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c13.setForeground(new java.awt.Color(255, 255, 255));
        c13.setText("13");
        c13.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c13.setBorderPainted(true);
        c13.setEnabled(false);
        c13.setOpaque(false);
        c13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c13ActionPerformed(evt);
            }
        });

        c9.setBackground(java.awt.Color.green);
        c9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c9.setForeground(new java.awt.Color(255, 255, 255));
        c9.setText("9");
        c9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c9.setBorderPainted(true);
        c9.setEnabled(false);
        c9.setOpaque(false);

        c5.setBackground(java.awt.Color.green);
        c5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c5.setForeground(new java.awt.Color(255, 255, 255));
        c5.setText("5");
        c5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c5.setBorderPainted(true);
        c5.setEnabled(false);
        c5.setOpaque(false);

        c2.setBackground(java.awt.Color.green);
        c2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setText("2");
        c2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        c2.setBorderPainted(true);
        c2.setEnabled(false);
        c2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(c6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c1))
                    .addComponent(c11))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c2)
                            .addComponent(c7))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c13)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(c8)
                                .addComponent(c3))))
                    .addComponent(c12))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(c4)
                        .addComponent(c9, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(c14))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c15)
                    .addComponent(c5)
                    .addComponent(c10))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1)
                    .addComponent(c2)
                    .addComponent(c3)
                    .addComponent(c4)
                    .addComponent(c5))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c10)
                    .addComponent(c9)
                    .addComponent(c8)
                    .addComponent(c7)
                    .addComponent(c6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c11)
                    .addComponent(c12)
                    .addComponent(c13)
                    .addComponent(c14)
                    .addComponent(c15))
                .addGap(38, 38, 38))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 310, 440, 260);

        jButton3.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        jButton3.setText("Log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(810, 551, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_MG_5462.0.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -30, 900, 620);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("seats");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(800, 170, 90, 20);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(700, 200, 59, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_aaaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  {                             
      c1.setOpaque(rootPaneCheckingEnabled);
      c1.setBackground(Color.green);
      c2.setOpaque(rootPaneCheckingEnabled);
      c2.setBackground(Color.green);
      c3.setOpaque(rootPaneCheckingEnabled);
      c3.setBackground(Color.green);
      c4.setOpaque(rootPaneCheckingEnabled);
      c4.setBackground(Color.green);
      c5.setOpaque(rootPaneCheckingEnabled);
      c5.setBackground(Color.green);
      c6.setOpaque(rootPaneCheckingEnabled);
      c6.setBackground(Color.green);
      c7.setOpaque(rootPaneCheckingEnabled);
      c7.setBackground(Color.green);
      c8.setOpaque(rootPaneCheckingEnabled);
      c8.setBackground(Color.green);
      c9.setOpaque(rootPaneCheckingEnabled);
      c9.setBackground(Color.green);
      c10.setOpaque(rootPaneCheckingEnabled);
      c10.setBackground(Color.green);
      c11.setOpaque(rootPaneCheckingEnabled);
      c11.setBackground(Color.green);
      c12.setOpaque(rootPaneCheckingEnabled);
      c12.setBackground(Color.green);
      c13.setOpaque(rootPaneCheckingEnabled);
      c13.setBackground(Color.green);
      c14.setOpaque(rootPaneCheckingEnabled);
      c14.setBackground(Color.green);
      c15.setOpaque(rootPaneCheckingEnabled);
      c15.setBackground(Color.green);
      
       c1.setEnabled(rootPaneCheckingEnabled);
       c2.setEnabled(rootPaneCheckingEnabled);
       c3.setEnabled(rootPaneCheckingEnabled); 
       c4.setEnabled(rootPaneCheckingEnabled);
       c5.setEnabled(rootPaneCheckingEnabled);
       c6.setEnabled(rootPaneCheckingEnabled);
       c7.setEnabled(rootPaneCheckingEnabled);
       c8.setEnabled(rootPaneCheckingEnabled);
       c9.setEnabled(rootPaneCheckingEnabled);
       c10.setEnabled(rootPaneCheckingEnabled);
       c11.setEnabled(rootPaneCheckingEnabled);
       c12.setEnabled(rootPaneCheckingEnabled);
       c13.setEnabled(rootPaneCheckingEnabled);
       c14.setEnabled(rootPaneCheckingEnabled);
       c15.setEnabled(rootPaneCheckingEnabled);
    
       
       Object str1 =  aaa.getSelectedItem();
       Object str2 =  ccc.getSelectedItem();
       Object date = (((JTextField)bbb.getDateEditor().getUiComponent()).getText()); 
       int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0,o=0;
       if (evt.getSource() == jButton1)
            
       {
           try
           {
               
 
               Class.forName("com.mysql.jdbc.Driver");
 
               Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/theatre", "root", "root");
 
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery("select a.movie_name,b.mid,b.show_date,b.seat_no from movie a,booking b where a.mid = b.mid ");
           
             while (rs.next()) { 
               {
                   String val1 = rs.getString(1);
                   String val2 = rs.getString(2);
                   String val3 = rs.getString(3);
                   String val5 = rs.getString(4);
                      
                   if ((val1.equals(str1))&&(val2.equals(str2)))
                   {
                       if (val3.equals(date))
                      {
                          if (val5.equals("1"))
                          {
                              c1.setEnabled(false);
                              c1.setBackground(Color.red);
                              a =1;
                          }
                          else if(val5.equals("2"))
                          {
                              c2.setEnabled(false);
                              c2.setBackground(Color.red);
                              b=1;
                          }
                          else if(val5.equals("3"))
                          {
                              c3.setEnabled(false);
                              c3.setBackground(Color.red);
                              c=1;
                          }
                          else if(val5.equals("4"))
                          {
                              c4.setEnabled(false);
                               c4.setBackground(Color.red);
                              d =1;
                          }
                          else if(val5.equals("5"))
                          {
                              c5.setEnabled(false);
                               c5.setBackground(Color.red);
                              e=1;
                          }
                          else if(val5.equals("6"))
                          {
                              c6.setEnabled(false);
                               c6.setBackground(Color.red);
                              f=1;
                          }
                          else if(val5.equals("7"))
                          {
                              c7.setEnabled(false);
                               c7.setBackground(Color.red);
                              g=1;
                          }
                          else if(val5.equals("8"))
                          {
                              c8.setEnabled(false);
                               c8.setBackground(Color.red);
                              h=1;
                          }
                          else if(val5.equals("9"))
                          {
                              c9.setEnabled(false);
                              c9.setBackground(Color.red);
                              i=1;
                          }
                          else if(val5.equals("10"))
                          {
                              c10.setEnabled(false);
                              c10.setBackground(Color.red);
                              j=1;
                          }
                          else if(val5.equals("11"))
                          {
                              c11.setEnabled(false);
                               c11.setBackground(Color.red);
                               k=1;
                          }
                          else if(val5.equals("13"))
                          {
                              c13.setEnabled(false);
                              c13.setBackground(Color.red);
                              l=1;
                          }
                          else if(val5.equals("14"))
                          {
                              c14.setEnabled(false);
                              c14.setBackground(Color.red);
                              m=1;
                          }
                          else if(val5.equals("15"))
                          {
                              c15.setEnabled(false);
                               c15.setBackground(Color.red);
                               n=1;
                          }
                          else if(val5.equals("12"))
                          {
                              c12.setEnabled(false);
                               c12.setBackground(Color.red);
                               o=1;
                          }
                         
                          
                      }
                     
                     
                   }
                  
               }   
           }
                  int su = a+b+c+d+e+f+g+h+i+j+k+l+m+n;
                  sss.setText(""+su);
                  
                  
              rs.close();
              st.close();
              con.close();
           }
     catch (SQLException ex)
           {
               System.out.print("exception is" + ex);
           } catch (ClassNotFoundException ex)
           {
               System.out.print("exception is" + ex);
           }
       }

       
    }          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new NewJFrame3().setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c13ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c7ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_c12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
         int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0,o=0;
         String a1="",a2="",a3="",a4="",a5="",a6="",a7="",a8="",a9="",a10="",a11="",a12="",a13="",a14="",a15="";
        
        if (c1.isSelected()== true)
        {
            a1="1";
            a=1;
        }
         if (c2.isSelected()== true)
        {
            a2="2";
            b=1;
            
        }
          if (c3.isSelected()== true)
        {
            c=1;
            a3="3";
            
        }
           if (c4.isSelected()== true)
        {
            d=1;a4="4";
        }
            if (c5.isSelected()== true)
        {
            e=1;a5="5";
        }
             if (c6.isSelected()== true)
        {
            f=1;a6="6";
        }
              if (c7.isSelected()== true)
        {
            g=1;a7="7";
        }
               if (c8.isSelected()== true)
        {
            h=1;a8="8";
        }
                if (c9.isSelected()== true)
        {
            i=1;a9="9";
        }
                 if (c10.isSelected()== true)
        {
            j=1;a10="10";
        }
                  if (c11.isSelected()== true)
        {
            k=1;a11="11";
        }
                   if (c12.isSelected()== true)
        {
            l=1;a12="12";
        }
                    if (c13.isSelected()== true)
        {
            m=1;a13="13";
        }
                     if (c14.isSelected()== true)
        {
            n=1;a14="14";
        }
                      if (c15.isSelected()== true)
        {
            o=1;a15="15";
        }
                      
               int ao = a+b+c+d+e+f+g+h+i+j+k+l+m+n+o;
               String aao = Integer.toString(ao);
               
               jLabel3.setText(a1+" "+a2+" "+a3+" "+a4+" "+a5+" "+a6+" "+a7+" "+a8+" "+a9+" "+a10+" "+a11+" "+a12+" "+a13+" "+a14+" "+a15);
               
               
        String s = jLabel3.getText();
        String str1 =  (String) aaa.getSelectedItem();
        String str2 =  (String)ccc.getSelectedItem();
        String date = (String)(((JTextField)bbb.getDateEditor().getUiComponent()).getText());
       
        this.setVisible(false);
        new NewJFrame5(str1,str2,date,s,aao).setVisible(true);                
        
        
        /*  {                                             
       Object str1 =  aaa.getSelectedItem();
       Object str2 =  ccc.getSelectedItem();
       Object date = (((JTextField)bbb.getDateEditor().getUiComponent()).getText()); 
       int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0;
       if (evt.getSource() == jButton1)
            
       {
           try
           {
               
 
               Class.forName("com.mysql.jdbc.Driver");
 
               Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/theatre", "root", "root");
 
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery("select a.movie_name,b.mid,b.shodate,b.sho,b.seatno from movie a,booking b where a.mid = b.mid ");
           
             while (rs.next()) { 
               {
                   Object val1 = rs.getString(1);
                   String val2 = rs.getString(2);
                   String val3 = rs.getString(3);
                   String val4 = rs.getString(4);
                   String val5 = rs.getString(5);
                      
                   if ((val1.equals(str1))&&(val2.equals(str2)))
                   {
                      if (val3.equals(date))
                      {
                          if (val5.equals("1"))
                          {
                              c1.setEnabled(false);
                              c1.setForeground(Color.red);
                              a =1;
                          }
                          else if(val5.equals("2"))
                          {
                              c2.setEnabled(false);
                              c2.setForeground(Color.red);
                              b=1;
                          }
                          else if(val5.equals("3"))
                          {
                              c3.setEnabled(false);
                              c3.setForeground(Color.red);
                              c=1;
                          }
                          else if(val5.equals("4"))
                          {
                              c4.setEnabled(false);
                              c4.setForeground(Color.red);
                              d =1;
                          }
                          else if(val5.equals("5"))
                          {
                              c5.setEnabled(false);
                              c5.setForeground(Color.red);
                              e=1;
                          }
                          else if(val5.equals("6"))
                          {
                              c6.setEnabled(false);
                              c6.setForeground(Color.red);
                              f=1;
                          }
                          else if(val5.equals("7"))
                          {
                              c7.setEnabled(false);
                              c7.setForeground(Color.red);
                              g=1;
                          }
                          else if(val5.equals("8"))
                          {
                              c8.setEnabled(false);
                              c8.setForeground(Color.red);
                              h=1;
                          }
                          else if(val5.equals("9"))
                          {
                              c9.setEnabled(false);
                              c9.setForeground(Color.red);
                              i=1;
                          }
                          else if(val5.equals("10"))
                          {
                              c10.setEnabled(false);
                              c10.setForeground(Color.red);
                              j=1;
                          }
                          else if(val5.equals("11"))
                          {
                              c11.setEnabled(false);
                              c12.setForeground(Color.red);
                              k=1;
                          }
                          else if(val5.equals("13"))
                          {
                              c13.setEnabled(false);
                              c13.setForeground(Color.red);
                              l=1;
                          }
                          else if(val5.equals("14"))
                          {
                              c14.setEnabled(false);
                              c14.setForeground(Color.red);
                              m=1;
                          }
                          else if(val5.equals("15"))
                          {
                              c15.setEnabled(false);
                              c15.setForeground(Color.red);
                              n=1;
                          }
                         
                         
                          
                      }
                     
                     
                   }
                  
               }   
           }
                  int su = a+b+c+d+e+f+g+h+i+j+k+l+m+n;
                  sss.setText(""+su);
                  
                  
              rs.close();
              st.close();
              con.close();
           }
     catch (SQLException ex)
           {
               System.out.print("exception is" + ex);
           } catch (ClassNotFoundException ex)
           {
               System.out.print("exception is" + ex);
           }
       }

       
    }
     
        
        String s = sss.getText();
        String str1 =  (String) aaa.getSelectedItem();
        String str2 =  (String)ccc.getSelectedItem();
        String date = (String)(((JTextField)bbb.getDateEditor().getUiComponent()).getText());
       
        this.setVisible(false);
        new NewJFrame5(str1,str2,date,s).setVisible(true);*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              this.setVisible(false);
               new log_out().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try
           {
 
               Class.forName("com.mysql.jdbc.Driver");
 
               Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/theatre", "root", "root");
 
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery("select movie_name from movie");
               aaa.removeAllItems();
             while (rs.next())
             { 
                   String val1 = rs.getString(1);
                   aaa.addItem(val1);
             }
                  
              rs.close();
              st.close();
              con.close();
           }
     catch (Exception e)
           {
               JOptionPane.showMessageDialog(null,"a...");
           } 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aaa;
    private com.toedter.calendar.JDateChooser bbb;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c14;
    private javax.swing.JCheckBox c15;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JComboBox<String> ccc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel sss;
    // End of variables declaration//GEN-END:variables
}
